server:
  port: 40000
spring:
  application:
    name: mall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
#        dashboard: localhost:8333
        dashboard: localhost:8082
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
  mvc:
    static-path-pattern: /static/**
mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10