spring:
  application:
    name: mall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8082
#        dashboard: localhost:8333
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
logging:
  level:
    com.rawchen.mall.search: error
#    org.springframework.cloud.openfeign: debug
#    org.springframework.cloud.sleuth: debug
server:
  port: 12000