spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
#        dashboard: localhost:8333
        dashboard: localhost:8082
  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
server:
  port: 20000
  # session存活时间
  servlet:
    session:
      timeout: 30m